# Generated by Django 3.0.14 on 2022-11-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_remove_product_price_productattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
