# Generated by Django 4.1.3 on 2022-11-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_brand_image_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to='brands_imgs/'),
        ),
    ]
