# Generated by Django 4.1.3 on 2022-11-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
