# Generated by Django 4.1.3 on 2022-11-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='materials',
            new_name='material',
        ),
    ]
